apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: email-extractor-s3-pvc
  namespace: email-extractor
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi # Match the PV storage size, though ignored
  volumeName: email-extractor-s3-pv # Name of our PV
